apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: middleware
  namespace: argocd
  # Annotations to control cleanup behavior
  annotations:
    argocd.argoproj.io/sync-options: "PrunePropagationPolicy=foreground,PruneLast=true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Middleware services like cert-manager, ingress-nginx, external-dns
  
  # Source repositories
  sourceRepos:
  - '*'
  
  # Allowed destinations
  destinations:
  - namespace: 'cert-manager'
    server: https://kubernetes.default.svc
  - namespace: 'ingress-nginx'
    server: https://kubernetes.default.svc
  - namespace: 'external-dns'
    server: https://kubernetes.default.svc
  
  # Cluster resource whitelist
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: admissionregistration.k8s.io
    kind: ValidatingAdmissionWebhook
  - group: admissionregistration.k8s.io
    kind: MutatingAdmissionWebhook
  - group: networking.k8s.io
    kind: IngressClass
  
  # Namespace resource whitelist
  namespaceResourceWhitelist:
  - group: ''
    kind: '*'
  - group: apps
    kind: '*'
  - group: networking.k8s.io
    kind: '*'
  - group: cert-manager.io
    kind: '*'
  - group: acme.cert-manager.io
    kind: '*'
  - group: rbac.authorization.k8s.io
    kind: '*'
  
  # Roles for this project
  roles:
  - name: middleware-admin
    description: Admin access to middleware project
    policies:
    - p, proj:middleware:middleware-admin, applications, *, middleware/*, allow
    - p, proj:middleware:middleware-admin, repositories, *, *, allow
    groups:
    - argocd-admins
