apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Monitoring services like Grafana, Prometheus, Loki
  
  # Source repositories
  sourceRepos:
  - '*'
  
  # Allowed destinations
  destinations:
  - namespace: 'prometheus'
    server: https://kubernetes.default.svc
  - namespace: 'grafana'
    server: https://kubernetes.default.svc
  - namespace: 'loki'
    server: https://kubernetes.default.svc
  - namespace: 'tempo'
    server: https://kubernetes.default.svc
  
  # Cluster resource whitelist
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: admissionregistration.k8s.io
    kind: ValidatingAdmissionWebhook
  - group: admissionregistration.k8s.io
    kind: MutatingAdmissionWebhook
  
  # Namespace resource whitelist
  namespaceResourceWhitelist:
  - group: ''
    kind: '*'
  - group: apps
    kind: '*'
  - group: networking.k8s.io
    kind: '*'
  - group: monitoring.coreos.com
    kind: '*'
  
  # Roles for this project
  roles:
  - name: monitoring-admin
    description: Admin access to monitoring project
    policies:
    - p, proj:monitoring:monitoring-admin, applications, *, monitoring/*, allow
    - p, proj:monitoring:monitoring-admin, repositories, *, *, allow
    groups:
    - argocd-admins
