apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: services
  namespace: argocd
  # Annotations to control cleanup behavior
  annotations:
    argocd.argoproj.io/sync-options: "PrunePropagationPolicy=foreground,PruneLast=true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Application services like JupyterHub and other user-facing services
  
  # Source repositories
  sourceRepos:
  - '*'
  
  # Allowed destinations
  destinations:
  - namespace: 'jupyter'
    server: https://kubernetes.default.svc
  - namespace: 'jupyterhub'
    server: https://kubernetes.default.svc
  
  # Cluster resource whitelist
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  
  # Namespace resource whitelist
  namespaceResourceWhitelist:
  - group: ''
    kind: '*'
  - group: apps
    kind: '*'
  - group: networking.k8s.io
    kind: '*'
  - group: policy
    kind: '*'
  - group: rbac.authorization.k8s.io
    kind: '*'
  - group: batch
    kind: '*'
  
  # Roles for this project
  roles:
  - name: services-admin
    description: Admin access to services project
    policies:
    - p, proj:services:services-admin, applications, *, services/*, allow
    - p, proj:services:services-admin, repositories, *, *, allow
    groups:
    - argocd-admins
