# JupyterHub Configuration
# Zero to JupyterHub (Z2JH) Configuration for Mac Pro / Kind Cluster
# Reference: https://z2jh.jupyter.org/en/stable/

# Proxy configuration
proxy:
  secretToken: "your-secret-token-here-change-this-in-production"
  service:
    type: ClusterIP  # Use with port-forward for Kind cluster
  chp:
    resources:
      requests:
        memory: 320Mi
        cpu: 0.1
      limits:
        memory: 1Gi
        cpu: 1
  traefik:
    resources:
      requests:
        memory: 512Mi
        cpu: 0.25
      limits:
        memory: 1Gi
        cpu: 1

# Hub configuration
hub:
  # Database configuration - SQLite for simplicity
  db:
    type: sqlite-pvc
    pvc:
      storageClassName: standard
      storage: 1Gi
  
  # Hub resources
  resources:
    requests:
      memory: 512Mi
      cpu: 0.25
    limits:
      memory: 1Gi
      cpu: 1
  
  # Authentication configuration
  config:
    JupyterHub:
      admin_access: true
      authenticator_class: 'dummy'  # Simple auth for development
    DummyAuthenticator:
      password: 'jupyter'  # Simple password for testing
    Authenticator:
      admin_users:
        - admin
        - jupyter
      allowed_users:
        - admin
        - jupyter
        - user1
        - user2
  
  # Additional hub configuration
  extraConfig:
    customConfig: |
      c.JupyterHub.logo_file = '/usr/local/share/jupyterhub/static/images/jupyter.png'
      c.JupyterHub.template_paths = ['/usr/local/share/jupyterhub/custom_templates/', 
                                     '/usr/local/share/jupyterhub/templates/']
      # Fix kernel connection issues
      c.KubeSpawner.enable_user_namespaces = False
      c.Spawner.default_url = '/lab'
  
  # Ensure hub can reach K8s API (disable NP and clear proxies)
  networkPolicy:
    enabled: false
  extraEnv:
    HTTP_PROXY: ""
    HTTPS_PROXY: ""
    http_proxy: ""
    https_proxy: ""
    NO_PROXY: ".svc,.cluster.local,localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
    no_proxy: ".svc,.cluster.local,localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"

# Single-user notebook configuration
singleuser:
  # Default image
  image:
    name: quay.io/jupyterhub/k8s-singleuser-sample
    tag: "4.2.0"
    pullPolicy: IfNotPresent
  
  # Start timeout
  startTimeout: 900
  
  # CPU/Memory limits
  cpu:
    limit: 1
    guarantee: 0.1
  memory:
    limit: 2G
    guarantee: 512M
  
  # Storage
  storage:
    type: dynamic
    dynamic:
      storageClass: standard
      storageAccessModes: ["ReadWriteOnce"]
      pvcNameTemplate: "jhub-claim-{username}"
    capacity: "2Gi"
    homeMountPath: /home/jovyan
    extraVolumes:
      - name: host-share
        hostPath:
          path: /mnt/host/jupyterhub
          type: DirectoryOrCreate
    extraVolumeMounts:
      - name: host-share
        mountPath: /home/jovyan/share
        readOnly: false
  
  # Default URL for users
  defaultUrl: "/lab"
  
  # File system group ID
  fsGid: 1000
  
  # Network policy - disabled for Kind cluster
  networkPolicy:
    enabled: false
  
  # Additional environment variables
  extraEnv:
    EDITOR: "nano"
    JUPYTER_ENABLE_LAB: "yes"
    RESTARTABLE: "yes"
  
  # Lifecycle hooks
  lifecycleHooks:
    postStart:
      exec:
        command:
          - "sh"
          - "-c"
          - >
            mkdir -p /home/jovyan/work /home/jovyan/share;

# Scheduling configuration
scheduling:
  userScheduler:
    enabled: false  # Disabled for Kind cluster
  
  podPriority:
    enabled: false
  
  userPlaceholder:
    enabled: false  # Disabled for Kind cluster

# Ingress configuration
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - jupyterhub.local
  pathSuffix: ""
  pathType: Prefix
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"

# RBAC
rbac:
  create: true

# Debug mode
debug:
  enabled: false

# Custom configuration for development
custom:
  # Additional labels
  commonLabels:
    app.kubernetes.io/part-of: jupyterhub
    environment: development
