# Cilium v1.17 - Minimal Production Configuration

# Cluster configuration
cluster:
  name: "iac-lab"
  id: 1

# Kube-proxy replacement
kubeProxyReplacement: true

# IPv4 configuration
ipv4:
  enabled: true
  # nativeRoutingCIDR will be set by Terraform from Kind's pod subnet

# Routing - native mode without tunneling
routingMode: "native"
autoDirectNodeRoutes: true

# IPAM
ipam:
  mode: kubernetes

# Masquerading
enableIPv4Masquerade: true
enableIPMasqAgent: false

# Basic Hubble setup
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

# Disable Prometheus ServiceMonitor (requires Prometheus Operator)
prometheus:
  enabled: false

# Basic resources
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 128Mi

# Security
policyEnforcementMode: "default"

# Disable encryption for now (can cause issues in Kind)
encryption:
  enabled: false
